### ISSUE TITLE
Firefox Compatibility Error

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#4]
There's some sort of compatibility issue that might be linked to the API that we're using with speech recognition. There's a type error on line 4 as shown below.

> TypeError: SpeechRecognition is not a constructor
> 
> ./src/components/Captions/Recognition/index.js
> src/components/Captions/Recognition/index.js:4
> 
>  1 | import React from 'react'
>   2 | 
>   3 | const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
>   4 | const recognition = new SpeechRecognition()
>   5 | recognition.lang = 'en-US'
>   6 | recognition.continuous = false
>   7 | recognition.interimResults = true

**Comment by angrave** [comment]
Not supported (yet) on Firefox - 
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Browser_compatibility

Also earlier versions of Chrome supported it with the "webkitSpeechRecognition" version -
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
"Support for Web Speech API speech recognition is currently limited to Chrome for Desktop and Android — Chrome has supported it since around version 33 but with prefixed interfaces, so you need to include prefixed versions of them, e.g. webkitSpeechRecognition."

We should gracefully handle this by suggesting that the browser does not support this and suggests the user uses Chrome browser.

**Comment by coolhands25** [comment]
It appears that Edge has a similar issue

**Comment by angrave** [comment]
^ I'd propose not doing a browser check or version; instead create the objects within a try-catch block: If an exception occurs then assume this html5 interface is not supported.

**Comment by timurjavid** [comment]
Instead of suggesting the user use Chrome, we should prevent webspeech API from loading if it's not compatible so ScribeAR can still load. We should notify the user that the browser they're using doesn't support webspeech and they will have to use Azure or another transcription method.

**Comment by harsh183** [comment]
I think this is better too. I only use Azure anyway but switching to Chrome is just another step for me.
